"""initial schema

Revision ID: 1c2253fc142e
Revises: 
Create Date: 2026-01-21 10:17:37.473341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c2253fc142e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('external_teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('team_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('team_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('energy_score', sa.Float(), nullable=True),
    sa.Column('engagement_score', sa.Float(), nullable=True),
    sa.Column('exploration_score', sa.Float(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('calculation_period_start', sa.DateTime(), nullable=True),
    sa.Column('calculation_period_end', sa.DateTime(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(), nullable=True),
    sa.Column('total_communications', sa.Integer(), nullable=True),
    sa.Column('avg_response_time', sa.Float(), nullable=True),
    sa.Column('participation_rate', sa.Float(), nullable=True),
    sa.Column('gini_coefficient', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_team_calculated', 'team_metrics', ['team_id', 'calculated_at'], unique=False)
    op.create_table('communications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('communication_type', sa.String(length=50), nullable=True),
    sa.Column('duration_minutes', sa.Float(), nullable=True),
    sa.Column('is_group_communication', sa.Integer(), nullable=True),
    sa.Column('is_cross_team', sa.Integer(), nullable=True),
    sa.Column('message_content', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('external_team_id', sa.Integer(), nullable=True),
    sa.Column('context', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['external_team_id'], ['external_teams.id'], ),
    sa.ForeignKeyConstraint(['receiver_id'], ['team_members.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['team_members.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_communication_type', 'communications', ['communication_type'], unique=False)
    op.create_index('idx_cross_team', 'communications', ['team_id', 'is_cross_team', 'timestamp'], unique=False)
    op.create_index('idx_sender_timestamp', 'communications', ['sender_id', 'timestamp'], unique=False)
    op.create_index('idx_team_timestamp', 'communications', ['team_id', 'timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_team_timestamp', table_name='communications')
    op.drop_index('idx_sender_timestamp', table_name='communications')
    op.drop_index('idx_cross_team', table_name='communications')
    op.drop_index('idx_communication_type', table_name='communications')
    op.drop_table('communications')
    op.drop_index('idx_team_calculated', table_name='team_metrics')
    op.drop_table('team_metrics')
    op.drop_table('team_members')
    op.drop_table('teams')
    op.drop_table('external_teams')
    # ### end Alembic commands ###
